const std = @import("std");

/// C ABI version exported by `aktorz_abi_version` and checked by the TypeScript loader.
pub const abi_version: u32 = 3;

pub const NativeTarget = struct {
    key: []const u8,
    zig: []const u8,
    file: []const u8,
};

/// Canonical packaged TypeScript shared-library matrix. The TypeScript twin is
/// generated from these rows at comptime.
pub const targets = [_]NativeTarget{
    .{ .key = "darwin-arm64", .zig = "aarch64-macos", .file = "libaktorz.dylib" },
    .{ .key = "darwin-x64", .zig = "x86_64-macos", .file = "libaktorz.dylib" },
    .{ .key = "linux-arm64-gnu", .zig = "aarch64-linux-gnu.2.17", .file = "libaktorz.so" },
    .{ .key = "linux-x64-gnu", .zig = "x86_64-linux-gnu.2.17", .file = "libaktorz.so" },
    .{ .key = "linux-arm64-musl", .zig = "aarch64-linux-musl", .file = "libaktorz.so" },
    .{ .key = "linux-x64-musl", .zig = "x86_64-linux-musl", .file = "libaktorz.so" },
    .{ .key = "win32-arm64", .zig = "aarch64-windows-gnu", .file = "aktorz.dll" },
    .{ .key = "win32-x64", .zig = "x86_64-windows-gnu", .file = "aktorz.dll" },
};

/// Generated contents of `typescript/native-spec.ts`.
pub const typescript_source =
    "// Generated by `zig build typescript-native-spec` from `src/typescript/native_spec.zig`.\n" ++
    "// Do not edit by hand.\n\n" ++
    std.fmt.comptimePrint("export const ABI_VERSION = {d}\n\n", .{abi_version}) ++
    "export type NativeLibraryTarget = {\n" ++
    "  readonly key: string\n" ++
    "  readonly file: string\n" ++
    "}\n\n" ++
    "export const NATIVE_LIBRARY_TARGETS = [\n" ++
    typescriptTargetRows(0) ++
    "] as const satisfies readonly NativeLibraryTarget[]\n";

pub fn targetByKey(key: []const u8) ?NativeTarget {
    for (targets) |target| {
        if (std.mem.eql(u8, target.key, key)) return target;
    }
    return null;
}

pub fn targetFor(target: std.Target) ?NativeTarget {
    var key_buf: [32]u8 = undefined;
    const arch = switch (target.cpu.arch) {
        .aarch64 => "arm64",
        .x86_64 => "x64",
        else => return null,
    };
    const key = switch (target.os.tag) {
        .macos => std.fmt.bufPrint(&key_buf, "darwin-{s}", .{arch}) catch return null,
        .windows => std.fmt.bufPrint(&key_buf, "win32-{s}", .{arch}) catch return null,
        .linux => blk: {
            const libc = if (target.abi.isMusl())
                "musl"
            else if (target.abi.isGnu())
                "gnu"
            else
                return null;
            break :blk std.fmt.bufPrint(&key_buf, "linux-{s}-{s}", .{ arch, libc }) catch return null;
        },
        else => return null,
    };
    return targetByKey(key);
}

fn typescriptTargetRows(comptime index: usize) []const u8 {
    if (index == targets.len) return "";
    const target = targets[index];
    return std.fmt.comptimePrint(
        "  {{ key: \"{s}\", file: \"{s}\" }},\n",
        .{ target.key, target.file },
    ) ++ typescriptTargetRows(index + 1);
}

test "packaged native target triples parse" {
    for (targets) |target| {
        _ = try std.Target.Query.parse(.{ .arch_os_abi = target.zig });
    }
}
